/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10/samples
 */

plugins {
    kotlin("jvm") version "2.0.21"
}

group = "com.t0xodile"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("net.portswigger.burp.extensions:montoya-api:+")
    implementation(files("bulkScan-all.jar"))
    implementation(files("turbo-intruder-all.jar"))
}

sourceSets {
    main {
        resources {
            srcDir("src/main/resources")
        }
    }
}

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.jar {
    manifest {
        attributes(
            "Implementation-Title" to "Single-packet Tunneller",
            "Implementation-Version" to version,
            "Burp-Extension-Name" to "Single-packet Tunneller",
            "Burp-Extension-Version" to version,
            "Burp-Extension-Suite-Min-Version" to "2023.10.0",
            "Burp-Extension-Suite-Max-Version" to "2024.99.99"
        )
    }


    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}